### ISSUE TITLE
內存一直增長

### ISSUE THREAD

**Issue by yuessir** [2881099/NJob#2]
每天跑定時任務
發現每跑完 (task finished)
內存會一直增長
VM內存撐不了太久....
大神請教如何解
@2881099

**Comment by 2881099** [comment]
有多少个任务？

**Comment by 2881099** [comment]
https://github.com/2881099/IdleBus/tree/master/IdleScheduler

如果任务多，可以看看这个

**Comment by yuessir** [comment]
> 
> 
> https://github.com/2881099/IdleBus/tree/master/IdleScheduler
> 
> 如果任务多，可以看看这个

**Comment by yuessir** [comment]
> 
> 
> > https://github.com/2881099/IdleBus/tree/master/IdleScheduler
> > 如果任务多，可以看看这个
目前跑OA 工作大概8-10任務 頻率從分鐘到周都有
只是程序內存持續增長 似乎無法釋放內存...
我再看看您提供的方案

**Comment by yuessir** [comment]
> 
> 
> 有多少个任务？

目前跑OA 工作大概8-10任務 頻率從分鐘到周都有
只是程序內存持續增長 似乎無法釋放內存...
我再看看您提供的方案

**Comment by 2881099** [comment]
先别了解，这几个任务 NJob 肯定可以。

用内存分析器看看是什么占用的再说。

**Comment by yuessir** [comment]
j.Run += (a, b) =>
                {
                    StringBuilder sbReivewerContent = new StringBuilder();
                    var p=new Person();
    
                    sbReivewerContent.Append(p.Name);
    
    
                };
    
                j.Error += (a, b) =>
                {
    
                    Console.WriteLine("{0} {1} ERROR：{2}", DateTime.Now, b.Def, b.Exception.Message);
                };
    
                j.Start();
    
    class OfficeNews
        {
            public string Age { get; set; }
            public string Content => "長內文";
        }

這是其中的片段 內存因為長內文不停增長

**Comment by yuessir** [comment]
這些variable 不是會 out of scope 而被回收嗎?

**Comment by 2881099** [comment]
如果没有被别的地方引用，会被回收

**Comment by yuessir** [comment]
> 
> 
> 如果没有被别的地方引用，会被回收
@2881099 
請問源碼哪一段可以看到handler (`RUN`)完成後會自動釋放內存或退訂**events**呢?貌似memory leak

**Comment by 2881099** [comment]
有没有重现的例子，做成 demo 发给我看看

**Comment by yuessir** [comment]
class TestAction
        {
            public NJobRunHandler MyRun()
            {
               
                return (a, b) =>
                {
                    string connectionString = System.Configuration.ConfigurationManager.AppSettings["con"];
                    var dal= new DAL();
                    var dt = dal.GetADAllUsers(connectionString);
                    var v = GetMailContent();
                };
            }
            public string GetMailContent()
            {
                return "長文本!長文本!長文本!長文本!長文本!長文本!";
    
            }
        }



```
static void Main(string[] args)
    {
      var j = new NJob();
                    var memory = new TestAction();
                    j.Run += memory.MyRun();
                    memory = null;//for test
                    GC.Collect(GC.MaxGeneration);
                    Console.WriteLine("GC.Collect");
                    j.Start();
    }
```
njob.text
`name1 SEC 3 null     `  

@2881099 以上代碼測試時發現內存不斷增長

**Comment by 2881099** [comment]
什么环境，我用 .netcore 3.1 运行5分钟没出现内存问题。

您的意思是 GetMailContent 返回的长文本内容导致的？他是静态的吗？

**Comment by yuessir** [comment]
> 
> 
> 什么环境，我用 .netcore 3.1 运行5分钟没出现内存问题。
> 
> 您的意思是 GetMailContent 返回的长文本内容导致的？他是静态的吗？
感謝測試
GetMailContent 不是static方法 ,TestAction都是動態實例
我使用您的Njob 在.NET framework 4.6 執行，傳統framework4.6 下,私猜想為先前訂閱的事件沒有被回收，您覺得呢?我錄製了5分鐘的重現視頻 在链接：https://pan.baidu.com/s/1b-RlbIyM02Qxuf872ad7Dw 
提取码：iyup

**Comment by yuessir** [comment]
@2881099  感謝您的測試 我這邊環境為.net framework 4.6 
我想我已經發現問題的原因了 _與NJOB無關_，由於程序實現OA流程，用到了微軟的AD， 在交叉測試發現原因，

當中有unmanaged 資源導致，我關閉issue了，如後續還是有相似情況我會在重開issue  
**感謝您這輕量而強大的工具**
